# Generated by Django 4.0.5 on 2022-07-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='num',
            field=models.BigIntegerField(verbose_name='№'),
        ),
    ]
