# Generated by Django 4.0.5 on 2022-07-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Org_bills',
            new_name='Bills',
        ),
    ]
