# Generated by Django 4.0.5 on 2022-07-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_bills_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='num',
            field=models.BigIntegerField(db_column='№', verbose_name='№'),
        ),
    ]
