# Generated by Django 4.0.5 on 2022-07-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_org_bills_bills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='id',
            field=models.BigIntegerField(default=None, primary_key=True, serialize=False, unique=True),
        ),
    ]
