# Generated by Django 4.0.5 on 2022-07-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_bills_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='id',
            field=models.BigIntegerField(default=None, primary_key=True, serialize=False, unique=True, verbose_name='№'),
        ),
    ]
